name: log_en_file
description: Un paquete para realizar registros en un archivo.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  get_it: ^7.2.0
  path: ^1.8.2
